### ISSUE TITLE
insertion sort algoritham

### ISSUE THREAD

**Issue by yakin18** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#110]
i write insertion sort algorithm please assign me

**Comment by srishti011** [comment]
Hi, I want to contribute to this issue. Can you please assign me?

**Comment by PrakashGatiyala** [comment]
> Hi, I want to contribute to this issue. Can you please assign me?

Can you go through readme file and create a new issue for yourself.

**Comment by PrakashGatiyala** [comment]
PR Merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/166

**Comment by PrakashGatiyala** [comment]
> Hi, I want to contribute to this issue. Can you please assign me?

Open a new issue for different algorithm
