### ISSUE TITLE
Alpha Beta pruning 

### ISSUE THREAD

**Issue by Sayak-singha** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#123]
Alpha-Beta pruning is not actually a new algorithm, rather an optimization technique for minimax algorithm. It reduces the computation time by a huge factor. This allows us to search much faster and even go into deeper levels in the tree.

**Comment by Sayak-singha** [comment]
Thank you for assigning me this issue I will start working on this shortly

**Comment by PrakashGatiyala** [comment]
PR merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/212
