### ISSUE TITLE
Partition Equal Subset Sum Algorithm

### ISSUE THREAD

**Issue by krati5** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#127]
Write a program on Partition Equal Subset Sum

**Comment by krati5** [comment]
Thankyou. I have created a pull request for it.
https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/156

**Comment by PrakashGatiyala** [comment]
PR Merged. https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/156
Closing it. Thanks for constitution @krati5
