### ISSUE TITLE
Fibonacci series recursion and lteration

### ISSUE THREAD

**Issue by Kumari-Chandni** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#129]
I would like to contribute for the Fibonacci Series implementation in C++.

**Comment by Kumari-Chandni** [comment]
I had solved the Fibonacci Series Problem
Pull Request link: https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/154

**Comment by PrakashGatiyala** [comment]
PR merged.
