### ISSUE TITLE
Kadane's Algorithm

### ISSUE THREAD

**Issue by Adyasha28** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#133]
I would like to contribute for the Kadane's Algorithm implementation in C++.

**Comment by PrakashGatiyala** [comment]
> I would like to contribute for the Kadane's Algorithm implementation in C++.

Sure

**Comment by Kinshuk2003** [comment]
i would like to contribute kadane's Algorithm implementation in python please assign it to me

**Comment by PrakashGatiyala** [comment]
PR merged.
