### ISSUE TITLE
Merge Sort Algorithm

### ISSUE THREAD

**Issue by Kinshuk2003** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#140]
i would like to work on this in c, c++, and python please assign it to me

**Comment by PrakashGatiyala** [comment]
> i would like to work on this in c, c++, and python please assign it to me

Sure.

**Comment by Kinshuk2003** [comment]
I have created a pr but am not able to link it with this issue

**Comment by PrakashGatiyala** [comment]
PR link: https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/252

**Comment by PrakashGatiyala** [comment]
> I have created a pr but am not able to link it with this issue

I've done. PR merged.
