### ISSUE TITLE
Enhance the CONTRIBUTING.md file 

### ISSUE THREAD

**Issue by PrakashGatiyala** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#143]
You have to Enhance the CONTRIBUTING.md file and make it more readable. 

_If you want to work upon it, comment here and I'll assign it to you._

**Comment by 0xPratyush** [comment]
hey, if the issue is still open and not assigned to anybody then i will be happy to work on this issue.

**Comment by PrakashGatiyala** [comment]
> hey, if the issue is still open and not assigned to anybody then i will be happy to work on this issue.

Sure, All the best.

**Comment by PrakashGatiyala** [comment]
PR merged
