### ISSUE TITLE
Greatest of the four integers

### ISSUE THREAD

**Issue by rahul09999** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#148]
I want to contribute in this repository by adding **Greatest of the four integer** problem using function in C++ language
Here it's link:- https://www.hackerrank.com/challenges/c-tutorial-functions/problem

**Comment by rahul09999** [comment]
> I want to contribute in this repository by adding **Greatest of the four integer** problem using function in C++ language

Please assign me this issue

**Comment by Sambhav250703** [comment]
I want to contribute in this repository by adding code in python for greatest of four integer

**Comment by PrakashGatiyala** [comment]
PR merged
