### ISSUE TITLE
Tower of Hanoi problem

### ISSUE THREAD

**Issue by HarshithSimha** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#176]
@PrakashGatiyala I want to work on this issue. So please assign this to me.

**Comment by PrakashGatiyala** [comment]
> @PrakashGatiyala I want to work on this issue. So please assign this to me.

sure

**Comment by AfonsoBernardes** [comment]
Hi @PrakashGatiyala, I find this problem very interesting and would like to implement a solution as well; I see one person already assigned, can I join or is this a "one person per problem" thing?

Thanks in advance.

**Comment by PrakashGatiyala** [comment]
> > @PrakashGatiyala I want to work on this issue. So please assign this to me.
> 
> sure

PR Merged. https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/189

**Comment by PrakashGatiyala** [comment]
> Hi @PrakashGatiyala, I find this problem very interesting and would like to implement a solution as well; I see one person already assigned, can I join or is this a "one person per problem" thing?
> 
> Thanks in advance.

Open new issue for different problem,
