### ISSUE TITLE
Selection Sort

### ISSUE THREAD

**Issue by RidhikaJoshi** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#181]

**Comment by RidhikaJoshi** [comment]
I would like to work on this issue.

**Comment by Rakteem007** [comment]
sir i would like to work on this issue.

**Comment by PrakashGatiyala** [comment]
> I would like to work on this issue.

Sure. All the best

**Comment by PrakashGatiyala** [comment]
> sir i would like to work on this issue.

Hi @Rakteem007 , Create a new issue for another algorithm which doesn't exist in repo code base.

**Comment by manmohan4142** [comment]
Hey @PrakashGatiyala 
Could you plz assign it to me i want to work on it

**Comment by PrakashGatiyala** [comment]
PR merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/197

**Comment by PrakashGatiyala** [comment]
> Hey @PrakashGatiyala Could you plz assign it to me i want to work on it

Create new issue for another algorithm
