### ISSUE TITLE
Bucket Sort

### ISSUE THREAD

**Issue by sanskarsri** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#182]
I would like to contribute to this issue please assign me

**Comment by Rakteem007** [comment]
I would like to work on this issue.

**Comment by PrakashGatiyala** [comment]
PR merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/183

**Comment by PrakashGatiyala** [comment]
> I would like to work on this issue.

Create issue for another algorithm.
