### ISSUE TITLE
Spirally Traversing a Matrix

### ISSUE THREAD

**Issue by BhumikaJena** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#201]
@PrakashGatiyala ,Can you please assign this issue to me?

**Comment by PrakashGatiyala** [comment]
> @PrakashGatiyala ,Can you please assign this issue to me?

Sure

**Comment by PrakashGatiyala** [comment]
PR Merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/206
