### ISSUE TITLE
Preorder tree traversal algorithm

### ISSUE THREAD

**Issue by PrakashGatiyala** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#95]
Write a Program for Preorder tree traversal [algorithm.](https://en.wikipedia.org/?title=Pre-order_traversal&redirect=no)
Programming languages choice: C/C++/Java/Python/JavaScript

_If you want to work upon it, comment here and I'll assign it to you._

**Comment by Rituraj-13** [comment]
Hey, I want to work on this, can you assign please me for this?

**Comment by PrakashGatiyala** [comment]
> Hey, I want to work on this, can you assign please me for this?

Sure, All the best!

**Comment by Rituraj-13** [comment]
> > Hey, I want to work on this, can you assign please me for this?
> 
> Sure, All the best!

Thanks

**Comment by PrakashGatiyala** [comment]
PR merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/174
