### ISSUE TITLE
Binary search algorithm

### ISSUE THREAD

**Issue by PrakashGatiyala** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#98]
Write a Program for binary search algorithm

Programming languages choice: C/C++/Java/Python/JavaScript

_If you want to work upon it, comment here and I'll assign it to you._

**Comment by Rituraj-13** [comment]
hey, can you please assign me for this?

**Comment by Rituraj-13** [comment]
Hey, I want to work on this, can you assign please me for this?

**Comment by Rimjhim20** [comment]
Hii, I want to work on this problem, can you plz assign me? @PrakashGatiyala

**Comment by PrakashGatiyala** [comment]
> Hii, I want to work on this problem, can you plz assign me? @PrakashGatiyala

Sure, All the best!

**Comment by Raj-saurabh** [comment]
Hey I would like to work on this issue using C++. 
If possible can u please assisn it to me.

**Comment by PrakashGatiyala** [comment]
Hi @Raj-saurabh Can you create new issue for the same.
It's already assigned to @Rimjhim20 .

**Comment by Raj-saurabh** [comment]
> Hi @Raj-saurabh Can you create new issue for the same. It's already assigned to @Rimjhim20 .

Okay will open a new issue soon and will let u know..

**Comment by PrakashGatiyala** [comment]
Hi @Rimjhim20  Your PR https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/175 is now merged.
Thanks for contribution Rimjhim.

**Comment by Rimjhim20** [comment]
Thank  You so much  @PrakashGatiyala
