### ISSUE TITLE
Knapsack algorithm

### ISSUE THREAD

**Issue by PrakashGatiyala** [PrakashGatiyala/hackerrank_problems-or-hackerearth_problems#99]
Write a Program for Knapsack algorithm in Python. 

_If you want to work upon it, comment here and I'll assign it to you._

**Comment by Rakteem007** [comment]
Hello sir, I want to work on this problem. Please assign this to me.

**Comment by PrakashGatiyala** [comment]
> Hello sir, I want to work on this problem. Please assign this to me.

Sure.  All the best

**Comment by Ashwani132003** [comment]
Hii sir, I can do this in python and c++ also.

**Comment by Rakteem007** [comment]
> > Hello sir, I want to work on this problem. Please assign this to me.
> 
> Sure. All the best

thank you sir .

**Comment by PrakashGatiyala** [comment]
Hi @Ashwani132003  I'm low on time. Can you create new issue. I will assign to you that.

**Comment by PrakashGatiyala** [comment]
PR merged https://github.com/PrakashGatiyala/hackerrank_problems-or-hackerearth_problems/pull/179
